### ISSUE TITLE
fix: upgrading opendj on startup throws unknown operand shell script error

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-opendj#64]
On some deployment, upgrade opendj from previous version to 4.5.0 (volumes are mounted), the following error is thrown:

```
INFO - entrypoint - 2023-01-09 08:32:48,464 - Trying to upgrade OpenDJ server
Traceback (most recent call last):
  File "/app/scripts/entrypoint.py", line 634, in <module>
    main()
  File "/app/scripts/entrypoint.py", line 199, in main
    run_upgrade()
  File "/app/scripts/entrypoint.py", line 149, in run_upgrade
    assert retcode == 0, "Failed to upgrade OpenDJ; reason={}".format(err.decode())
AssertionError: Failed to upgrade OpenDJ; reason=sh: -f: unknown operand
```

Note: on some deployment, the issue is not thrown but can be reproduced manually by running `/opt/opendj/upgrade` script inside the pod.

**Comment by iromli** [comment]
Applied in `4.5.0-4` and `5.0.0_dev` images
