### ISSUE TITLE
Failed to generate PKCS12 file

### ISSUE THREAD

**Issue by codejamninja** [GluuFederation/docker-opendj#7]
I get the following error from the `config-init` container when running with kubernetes.

```
# ========================================================================================= #
# Gluu License Agreement: https://github.com/GluuFederation/gluu-docker/blob/3.1.5/LICENSE. #
# The use of Gluu Server Docker Edition is subject to the Gluu Support License. #
# ========================================================================================= #
Config backend is ready.
Secret backend is ready.
Generating config and secret.
adding secret 'encoded_salt'
adding config 'orgName'
adding config 'country_code'
adding config 'state'
adding config 'city'
adding config 'hostname'
adding config 'admin_email'
adding config 'default_openid_jks_dn_name'
adding secret 'pairwiseCalculationKey'
adding secret 'pairwiseCalculationSalt'
adding config 'jetty_base'
adding config 'fido2ConfigFolder'
adding config 'ldap_init_host'
adding config 'ldap_init_port'
adding config 'ldap_port'
adding config 'ldaps_port'
adding secret 'ldap_truststore_pass'
adding config 'ldap_type'
adding config 'ldap_binddn'
adding config 'ldap_site_binddn'
adding config 'ldapTrustStoreFn'
adding secret 'ldap_ssl_cert'
adding secret 'ldap_ssl_key'
adding secret 'ldap_ssl_cacert'
Traceback (most recent call last):
File "/opt/config-init/scripts/entrypoint.py", line 1148, in <module>
cli()
File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/opt/config-init/scripts/entrypoint.py", line 995, in generate
inum_appliance)
File "/opt/config-init/scripts/entrypoint.py", line 281, in generate_ctx
ctx["config"]["hostname"],
File "/opt/config-init/scripts/entrypoint.py", line 175, in generate_pkcs12
assert retcode == 0, "Failed to generate PKCS12 file; reason={}".format(err)
AssertionError: Failed to generate PKCS12 file; reason=pkcs12: Use -help for summary.
```

**Comment by codejamninja** [comment]
I was able to get passed this error. I was passing along wrong configuration.
